#app:
app:
  version: '@project.version@'
  cors-allowed-origins: [ "*" ]
  upload-dir:
  temporary-user-access-duration: P1D
  temporary-user-name: "Временный ученик #%s"
  first-admin:
    username: admin
    name: admin
    password: admin
jwt:
  max-refresh-tokens-per-user: 5
  secret: fill-me-later
  access-duration: PT5M
  refresh-duration: P90D
spring:
  jmx:
    default-domain: com.a6raywa1cher.mucservingboxspring
    unique-names: true
spring.jackson.mapper.DEFAULT_VIEW_INCLUSION: true
spring.servlet.multipart.max-file-size: 100MB
spring.servlet.multipart.max-request-size: 100MB
# ===============================
# DB CONNECTION
# ===============================
spring.datasource.url: # REQUIRED test database jdbc url
spring.datasource.username: # REQUIRED test database username
spring.datasource.password: # REQUIRED test database password
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: create
spring.jpa.properties.hibernate.default_schema: public
spring.jpa.properties.hibernate.dialect: com.a6raywa1cher.mucservingboxspring.utils.hibernate.PostgreSqlDialectFixed
spring.jpa.properties.hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false